### ISSUE TITLE
run-extractor success but data incorrect

### ISSUE THREAD

**Issue by hiepcs** [hialan-org/dod_watcher#11]
When i run extractor to get stock history, it run success but when I check in db, the date value is incorrect.
![image](https://user-images.githubusercontent.com/20101744/76093981-b96e1380-5f76-11ea-8ee2-2440e0b18d37.png)

**Comment by anuragjha** [comment]
The field I was taking from IEX response, had time (3:56:59PM) for some stocks. So I am now taking latestUpdate instead of latestTime now. And put it in the table to test.

[issue_call_aapl,csco.txt](https://github.com/hialan-org/dod_watcher/files/4301305/issue_call_aapl.csco.txt)
