### ISSUE TITLE
run-extractor duplicate data

### ISSUE THREAD

**Issue by hiepcs** [hialan-org/dod_watcher#13]
When someone run api /run-extractor on the same day, it will generate two duplicate row of stock data, can we just update the data on that day if user rerun it?
![image](https://user-images.githubusercontent.com/20101744/76095035-71e88700-5f78-11ea-864d-b08cb3ecdfd7.png)

**Comment by hiepcs** [comment]
@anuragjha Is this one completed?

**Comment by anuragjha** [comment]
completed

**Comment by anuragjha** [comment]
Completed - by first deleting rows for the date and then adding new rows.
