### ISSUE TITLE
Get profit day by day, with start day and end day

### ISSUE THREAD

**Issue by hiepcs** [hialan-org/dod_watcher#19]
Get a list of profit by the selected user (userId), day by day, with a start date and end date

**Comment by anuragjha** [comment]
assuming need overall profit

**Comment by anuragjha** [comment]
api - /user-profit/{SYM}
for overall, use api - /user-profit/overall

**Comment by anuragjha** [comment]
Currently:
user-profit/history/{userId}/{stockId}/{startDateStr}/{endDateStr}
class - UserProfitController
  method - getUserProfitHistory

**Comment by anuragjha** [comment]
example api - /user-profit/history/0?startDateStr=03-06-2020&endDateStr=03-18-2020
