### ISSUE TITLE
Get list of stock in selected day

### ISSUE THREAD

**Issue by hiepcs** [hialan-org/dod_watcher#21]
Get a list of stock (symbol, company name, price) in selected day

**Comment by anuragjha** [comment]
api:
/stock-history/{dateStr}

**Comment by anuragjha** [comment]
checking url

**Comment by anuragjha** [comment]
working - http://127.0.0.1:3000/stocks/stock-history/04-08-2020

**Comment by anuragjha** [comment]
anu_dev f79c0e4
